name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Update Workloads
      run: |
        dotnet workload update
        dotnet workload restore
    - name: Install Workloads
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore eShop.Web.slnf
    - name: Build
      run: dotnet build eShop.Web.slnf --no-restore
    - name: Test
      run: dotnet test eShop.Web.slnf --no-build --verbosity normal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Build and push container images to ACR
      run: az acr task run --registry ${{ secrets.ACR }} --name buildtask-catalogapi
