name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Update Workloads
      run: |
        dotnet workload update
        dotnet workload restore
    - name: Install Workloads
      run: dotnet workload install aspire
    - name: Restore dependencies
      run: dotnet restore src/Catalog.API/Catalog.API.csproj
    - name: Build
      run: dotnet build src/Catalog.API/Catalog.API.csproj --no-restore
    - name: Test
      run: dotnet test src/Catalog.API/Catalog.API.csproj --no-build --verbosity normal
